### PR TITLE
Added ==operator

### PR DESCRIPTION
**Pull request by Jesperobb**
Created ==operator

### CODE REVIEW

**Comment by Gian1080** [comment]
It looks good, have you tested the results to make sure it is working?

**Comment by Obbesjesper** [comment]
> It looks good, have you tested the results to make sure it is working?

Yes, I have tested it but not pushing it because the code has no reason to be in release.

**Comment by Jesperobb** [comment]
> It looks good, have you tested the results to make sure it is working?

I just added CATCH2 test cases!

**Comment by Gian1080** [comment]
Ok, well done!

**Pull request merged**
